import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
/**
 * YAML generator + sidecar writer.
 *
 * Produces a complete providers + equivalence block for models.yml.
 * Writes to a SIDECAR file only — NEVER touches models.yml.
 */
import type { EnrichedModel, GenerateResult, NineRouterConfig } from "./types";

export function generateYamlBlock(models: EnrichedModel[], config: NineRouterConfig): string {
  const lines: string[] = [
    "# Generated by nine-router-sync",
    `# Timestamp: ${new Date().toISOString()}`,
    "# Review, then copy into ~/.omp/agent/models.yml under providers:",
    "",
    "providers:",
    `  ${config.providerId}:`,
    `    baseUrl: ${config.baseUrl}`,
  ];

  if (config.apiKey) {
    const isEnv = /^[A-Z_][A-Z0-9_]*$/.test(config.apiKey);
    lines.push(
      isEnv ? `    apiKey: ${config.apiKey}` : `    # apiKey: ${config.apiKey}  # ← review before uncommenting`,
    );
  }

  lines.push("    api: openai-completions");

  if (models.length > 0) {
    lines.push("    models:");
    for (const m of models) {
      lines.push(`      - id: ${m.id}`);
      lines.push(`        name: ${escapeYamlString(m.name)}`);
      lines.push(`        api: ${m.api || "openai-completions"}`);
      if (m.thinking?.length)
        lines.push(`        thinking:\n          mode: effort\n          efforts: [${m.thinking.join(", ")}]`);
      lines.push("        cost:");
      lines.push(`          input: ${m.cost.input}`);
      lines.push(`          output: ${m.cost.output}`);
      lines.push(`          cacheRead: ${m.cost.cacheRead}`);
      lines.push(`          cacheWrite: ${m.cost.cacheWrite}`);
      lines.push(`        contextWindow: ${m.contextWindow}`);
      lines.push(`        maxTokens: ${m.maxTokens}`);
      if (m.enrichmentSource === "heuristic") {
        lines.push("        # ⚠ metadata from heuristics — verify manually");
      }
      lines.push("");
    }
  }

  // Canonical equivalence overrides
  const canonicalModels = models.filter((m) => m.canonicalId);
  if (canonicalModels.length > 0) {
    lines.push("equivalence:");
    lines.push("  overrides:");
    for (const m of canonicalModels) {
      lines.push(`    ${config.providerId}/${m.id}: ${m.canonicalId}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function saveSidecar(yamlBlock: string, outputPath: string): string {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, yamlBlock, "utf-8");
  return outputPath;
}

export function buildResult(
  modelsFound: number,
  enriched: number,
  heuristicDefaults: number,
  skipped: number,
  errors: string[],
  yamlBlock: string,
  outputPath: string,
): GenerateResult {
  return { modelsFound, enriched, heuristicDefaults, skipped, errors, yamlBlock, outputPath };
}

function escapeYamlString(s: string): string {
  if (/[":{}[\],&*#?|<>!%@`]/.test(s) || s.includes("\\")) {
    return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  if (s.length === 0 || s !== s.trim()) return `"${s}"`;
  return s;
}
